# ==========================================================
# 📥 PRE-LANDING LAYER
# ==========================================================

pre_landing:
  write_mode: append

  transactions:

    # ----------------------------
    # 🎯 Target Table (UC Managed)
    # ----------------------------
    catalog: retail_medallion_lakehouse
    target_schema: pre_landing
    table_name: transactions

    # ----------------------------
    # 📡 Source Info
    # ----------------------------
    input_path: "https://raw.githubusercontent.com/Vignesh-1512/data-engineering-project-practice/feature/brazillian_e-commerce/projects/retail_medallion_lakehouse/data/transactional_dataset.json"
    file_type: json

    # ----------------------------
    # 🌍 Translation Config
    # ----------------------------
    translation:
      catalog: retail_medallion_lakehouse
      schema: translation_dataset
      table_name: language_converter
      source_column: Column_Name
      target_column: Convert_Into
      apply_on:
        - root
        - items

    # ----------------------------
    # 🔄 Transformations
    # ----------------------------
    explode_columns:
      - items

    contacts:
      parent: "customer.contacts"
      type_field: "type"
      value_field: "value"
      mappings:
        email: "customer_email"
        phone: "customer_phone"

    # ----------------------------
    # 📑 Final Column Selection
    # ----------------------------
    select_columns:
      - "transaction_id"
      - "customer.cust_id as customer_id"
      - "customer.name as customer_name"
      - "item.product_id"
      - "item.product_name"
      - "item.qty as quantity"
      - "item.unit_price as price"
      - "transaction_ts"
      - "location"


  payments:
    catalog: retail_medallion_lakehouse
    target_schema: pre_landing
    table_name: payments

    input_path: "https://raw.githubusercontent.com/Vignesh-1512/data-engineering-project-practice/feature/brazillian_e-commerce/projects/retail_medallion_lakehouse/data/payment_dataset.json"
    file_type: json
    load_type: full

    select_columns:
      - payment_id
      - transaction_id
      - customer_id
      - amount_gross
      - discount_percent
      - discount_amount
      - shipping_fee
      - amount_charged
      - currency
      - payment_method
      - payment_gateway
      - payment_status
      - gateway_response_code
      - payment_ts
      - lineage_source

  products:
    catalog: retail_medallion_lakehouse
    target_schema: pre_landing
    table_name: products

    input_path: "/mnt/data/product_dataset.json"
    file_type: json
    load_type: full

    select_columns:
      - product_id
      - product_name
      - category
      - brand
      - price
      - cost
      - created_ts


# ==========================================================
# 📥 LANDING LAYER
# ==========================================================
landing:
    write_mode: overwrite

    transactions:
        #------------------------------------
        # SOURCE
        #------------------------------------
        catalog: retail_medallion_lakehouse
        source_schema: pre_landing
        source_table: transactions
        #------------------------------------
        # TARGET
        #------------------------------------
        target_schema: landing
        target_table: landing_transactions

        #------------------------------------
        # CAST RULE
        #------------------------------------
        casts:
            transaction_ts: timestamp
            price: double
            quantity: bigint
        
        #------------------------------------
        # VALIDATION
        #------------------------------------
        not_null_columns:
            - transaction_id
            - product_id
        
        positive_columns:
            - price
            - quantity
        trim_strings: true

        #------------------------------------
        # AUDIT + LINEAGE
        #------------------------------------

        overwrite_audit: true
        lineage_value: pre_landing

        #------------------------------------
        # PARTITION
        #------------------------------------
        partition_column: transaction_ts
        partition_type: year

        primary_keys:
            - transaction_id
            - product_id

    payments:
        # -------------------------
        # SOURCE
        # -------------------------
        catalog: retail_medallion_lakehouse
        source_schema: pre_landing
        source_table: payments

        # -------------------------
        # TARGET
        # -------------------------
        target_schema: landing
        target_table: landing_payments

        # -------------------------
        # CAST RULES
        # -------------------------
        casts:
            payment_ts: timestamp
            amount_gross: double
            discount_percent: double
            discount_amount: double
            shipping_fee: double
            amount_charged: double

        # -------------------------
        # VALIDATIONS
        # -------------------------
        not_null_columns:
            - payment_id
            - transaction_id

        positive_columns:
            - amount_charged

        trim_strings: true

        # -------------------------
        # DEDUP (OPTIONAL BUT SAFE)
        # -------------------------
        primary_keys:
            - payment_id

        # -------------------------
        # AUDIT + LINEAGE
        # -------------------------
        overwrite_audit: true
        lineage_value: pre_landing

        # -------------------------
        # PARTITION
        # -------------------------
        partition_column: payment_ts
        partition_type: year